version: '3'

services:
 
 haproxy:
  image:  haproxy:2.1 
  container_name: haproxy
  hostname: haproxy
  restart: always
  ports:
    - "5672:5672"
    - "1936:1936"

  environment:
      - TZ=Europe/Copenhagen
  
  volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro  